import { Review, Invite, BusinessSettings, Profile } from './supabase/types';

export const DEFAULT_BUSINESS = {
  id: "demo-ratingpulse",
  name: "RatingPulse",
  category: "Software & Reputation Management",
  address: "Rochester, NY",
  phone: "(585) 360-2026",
  placeId: "demo_ratingpulse_place_id",
  rating: 5.0,
  totalReviews: 48,
  reviewUrl: "https://search.google.com/local/writereview?placeid=demo_ratingpulse_place_id",
  isVerified: true,
};

export const DEMO_BUSINESS = DEFAULT_BUSINESS;

export const DEMO_PROFILE: Profile = {
  id: 'usr_mock_001',
  email: 'team@ratingpulse.co',
  full_name: 'Alex Rivera',
  business_name: 'RatingPulse',
  business_category: 'Software & Reputation Management',
  google_place_id: 'demo_ratingpulse_place_id',
  formatted_address: 'Rochester, NY',
  review_url: 'https://search.google.com/local/writereview?placeid=demo_ratingpulse_place_id',
  google_rating: 5.0,
  google_review_count: 48,
  google_connected: true,
  phone: '(585) 360-2026',
  stripe_customer_id: null,
  stripe_subscription_id: null,
  plan_status: 'trialing',
  created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
  updated_at: new Date().toISOString(),
};

export const DEMO_SETTINGS: BusinessSettings = {
  id: 'set_mock_001',
  user_id: 'usr_mock_001',
  brand_voice: 'friendly_professional',
  auto_publish_5_star: false,
  custom_keywords: ['automated review invites', 'Google review sync', 'AI review replies', '5-star reviews'],
  sms_template: 'Hi {{customer_name}}, thank you for choosing {{business_name}}! Could you take 30 seconds to leave us a quick review on Google? {{review_link}}',
  notify_email: true,
  notify_sms: true,
  notify_negative_enabled: true,
  notify_negative_email: true,
  notify_negative_sms: true,
  notify_negative_phone: '',
  notify_positive_enabled: true,
  notify_positive_email: true,
  notify_positive_sms: false,
  notification_email: 'team@ratingpulse.co',
  notification_phone: '(585) 360-2026',
  created_at: new Date().toISOString(),
};

export const DEMO_REVIEWS: Review[] = [
  {
    id: 'rev-101',
    user_id: 'usr_mock_001',
    business_id: 'usr_mock_001',
    place_id: 'demo_ratingpulse_place_id',
    author_name: 'Sarah Jenkins',
    author_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&h=120&fit=crop&crop=face',
    rating: 5,
    review_text: 'RatingPulse revolutionized our local search ranking! We gained 45+ new 5-star Google reviews in the first month. The automated 1-tap SMS invites are completely frictionless.',
    review_date: new Date(Date.now() - 2 * 3600000).toISOString(),
    ai_draft_reply: "Hi Sarah, thank you for choosing RatingPulse! We are thrilled to hear our review automation helped skyrocket your Google reviews and local ranking. Looking forward to your continued growth!",
    published_reply: null,
    status: 'pending_approval',
    sentiment: 'positive',
    keywords_used: ['automated review invites', 'Google review sync', 'RatingPulse'],
    created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: 'rev-102',
    user_id: 'usr_mock_001',
    business_id: 'usr_mock_001',
    place_id: 'demo_ratingpulse_place_id',
    author_name: 'David Montgomery',
    author_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&h=120&fit=crop&crop=face',
    rating: 5,
    review_text: "Incredible platform! The 1-tap AI review replies save our team hours every week. Super clean dashboard, instantaneous sync, and exceptional reliability.",
    review_date: new Date(Date.now() - 5 * 3600000).toISOString(),
    ai_draft_reply: "Hi David! Thank you for the glowing feedback. We are delighted to know our AI review reply engine is saving your team valuable hours every week. We appreciate your partnership!",
    published_reply: null,
    status: 'pending_approval',
    sentiment: 'positive',
    keywords_used: ['AI review replies', 'RatingPulse', 'reputation management'],
    created_at: new Date(Date.now() - 5 * 3600000).toISOString(),
  },
  {
    id: 'rev-103',
    user_id: 'usr_mock_001',
    business_id: 'usr_mock_001',
    place_id: 'demo_ratingpulse_place_id',
    author_name: 'Elena Rostova',
    author_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&h=120&fit=crop&crop=face',
    rating: 5,
    review_text: 'Our client reviews surged by 340% within 60 days of launching RatingPulse. The automated private feedback safeguard ensures our customer service is always top-tier.',
    review_date: new Date(Date.now() - 24 * 3600000).toISOString(),
    ai_draft_reply: "Thank you for your heartwarming feedback, Elena! Helping businesses collect authentic 5-star customer feedback is our mission. Thank you for choosing RatingPulse!",
    published_reply: "Thank you for your heartwarming feedback, Elena! Helping businesses collect authentic 5-star customer feedback is our mission. Thank you for choosing RatingPulse!",
    status: 'published',
    sentiment: 'positive',
    keywords_used: ['5-star reviews', 'customer feedback', 'RatingPulse'],
    published_at: new Date(Date.now() - 22 * 3600000).toISOString(),
    created_at: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
  {
    id: 'rev-104',
    user_id: 'usr_mock_001',
    business_id: 'usr_mock_001',
    place_id: 'demo_ratingpulse_place_id',
    author_name: 'Robert Chen',
    author_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&h=120&fit=crop&crop=face',
    rating: 5,
    review_text: 'High-converting SMS review invitations and flawless Google Places integration. Our organic search ranking skyrocketed to #1 locally.',
    review_date: new Date(Date.now() - 48 * 3600000).toISOString(),
    ai_draft_reply: "Hi Robert, thank you for your kind 5-star review! We are glad to hear our SMS invitation dispatch and Google Places integration helped achieve your #1 ranking.",
    published_reply: "Hi Robert, thank you for your kind 5-star review! We are glad to hear our SMS invitation dispatch and Google Places integration helped achieve your #1 ranking.",
    status: 'published',
    sentiment: 'positive',
    keywords_used: ['SMS review invitations', 'RatingPulse', 'Google Places integration'],
    published_at: new Date(Date.now() - 45 * 3600000).toISOString(),
    created_at: new Date(Date.now() - 48 * 3600000).toISOString(),
  }
];

export const DEMO_INVITES: Invite[] = [
  {
    id: 'inv-301',
    user_id: 'usr_mock_001',
    customer_name: 'Jessica Reynolds',
    customer_phone: '+1 (555) 849-2910',
    customer_email: 'jessica.reynolds@example.com',
    service_type: 'Software Setup & Onboarding',
    status: 'reviewed',
    sent_at: new Date(Date.now() - 3 * 3600000).toISOString(),
    review_received_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    rating_received: 5,
  },
  {
    id: 'inv-302',
    user_id: 'usr_mock_001',
    customer_name: 'Michael Chang',
    customer_phone: '+1 (555) 492-1082',
    customer_email: 'michael.chang@example.com',
    service_type: 'Google Review Campaign',
    status: 'opened',
    sent_at: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
  {
    id: 'inv-303',
    user_id: 'usr_mock_001',
    customer_name: 'Amanda Taylor',
    customer_phone: '+1 (555) 782-9013',
    customer_email: 'amanda.taylor@example.com',
    service_type: 'Reputation Management Audit',
    status: 'delivered',
    sent_at: new Date(Date.now() - 6 * 3600000).toISOString(),
  },
  {
    id: 'inv-304',
    user_id: 'usr_mock_001',
    customer_name: 'Brian Kowalski',
    customer_phone: '+1 (555) 301-4491',
    customer_email: 'brian.k@example.com',
    service_type: 'Review Ingestion Consultation',
    status: 'sent',
    sent_at: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: 'inv-305',
    user_id: 'usr_mock_001',
    customer_name: 'Lisa Morales',
    customer_phone: '+1 (555) 619-8820',
    customer_email: 'lisa.morales@example.com',
    service_type: 'AI Review Reply Setup',
    status: 'reviewed',
    sent_at: new Date(Date.now() - 28 * 3600000).toISOString(),
    review_received_at: new Date(Date.now() - 27 * 3600000).toISOString(),
    rating_received: 5,
  }
];
